apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.flask.name }}-cluster-service

spec:
  type: {{.Values.flask.service.type }}

  ports:
    - port: 80
      targetPort: {{ .Values.flask.image.exposePort }}
  selector:
    app: {{ .Values.flask.name }}
