apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.nginx.name }}-lb-service

spec:
  type: {{ .Values.nginx.service.type }}

  ports:
    - port: 80
      targetPort: {{ .Values.nginx.image.exposePort }}
  selector:
    app: {{.Values.nginx.name }}
