apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.nginx.name }}-deployment

spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
        - name: nginxapp
          image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.nginx.image.exposePort }}